// cliente/src/components/Scaffold.tsx
import { Outlet } from "react-router";

export default function Scaffold({ TopBar, BottomBar, children }: any) {
  return (
    <div className="w-full h-svh flex flex-col overflow-hidden">
      {TopBar && TopBar}
      <main className="flex-1 overflow-y-auto">
        {children ? children : <Outlet />}
      </main>
      {BottomBar && BottomBar}
    </div>
  );
}

// cliente/src/layouts/Scaffold.vue
<script setup>
import { computed } from 'vue';
import BottomNav from '../components/BottomNav.vue';
import { useRoute } from 'vue-router';

const route = useRoute();

const activeTopBar = computed(() => route.meta.topBar);
const activeBottomBar = computed(() => route.meta.bottomBar);
</script>

<template>
    <div class="c-container">
        <component :is="activeTopBar" v-if="activeTopBar" />
        <main class="c-content">
            <RouterView />
        </main>
        <component :is="activeBottomBar" v-if="activeBottomBar" />
    </div>
</template>

<style scoped>
.c-container {
    width: 100%;
    height: 100svh;

    display: flex;
    flex-direction: column;

    overflow: hidden;
}


.c-content {
    width: 100%;
    height: 100%;
    overflow-y: auto;
}
</style>
